packages:
  - .
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.4.0+sha512-VhKBB+lNYczcZ1C5iwJIWborOznelf3RAND8NPapFDQpWR/XzWz/fIbZyq7xrLC9JpjdToKY0FU2UqVIAJvsFQ==
loglevel: info
onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - esbuild
  - msgpackr-extract
preferFrozenLockfile: true
publicHoistPattern:
  - "@commitlint/cli"
  - "@commitlint/cz-commitlint"
  - husky
  - lint-staged
  - markdownlint-cli2
  - markdownlint-cli2-formatter-codequality
