packages:
  - .
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.4.1+sha512-eL4PUMUXO0/WmoBtTRZBEPc8UudB/L74df6KoyS3EmwscDi7gAMJAJNUtzq7rjRIWrujdxKKtvXBHEpPzl+IUw==
loglevel: info
onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - esbuild
  - msgpackr-extract
preferFrozenLockfile: true
publicHoistPattern:
  - "@commitlint/cli"
  - "@commitlint/cz-commitlint"
  - husky
  - lint-staged
  - markdownlint-cli2
  - markdownlint-cli2-formatter-codequality
