/**
 * Init command - bootstrap lint-staged configuration.
 *
 * @internal
 */
import { dirname } from "node:path";
import { isDeepStrictEqual } from "node:util";
import { Command, Options } from "@effect/cli";
import { FileSystem } from "@effect/platform";
import type { SectionBlock } from "@savvy-web/silk-effects";
import { BiomeSchemaSync, ManagedSection, SyncResult } from "@savvy-web/silk-effects";
import { Effect } from "effect";
import type { JsoncFormattingOptions } from "jsonc-effect";
import { applyEdits, modify, parse } from "jsonc-effect";
import {
	DEFAULT_CONFIG_PATH,
	HUSKY_HOOK_PATH,
	MARKDOWNLINT_CONFIG_PATH,
	POST_CHECKOUT_HOOK_PATH,
	POST_MERGE_HOOK_PATH,
	preCommitBlock,
	shellScriptsBlock,
} from "../sections.js";
import { MARKDOWNLINT_CONFIG, MARKDOWNLINT_SCHEMA, MARKDOWNLINT_TEMPLATE } from "../templates/markdownlint.gen.js";

/** Unicode checkmark symbol. */
const CHECK_MARK = "\u2713";

/** Unicode warning symbol. */
const WARNING = "\u26A0";

/** Executable file permission mode. */
const EXECUTABLE_MODE = 0o755;

/** Formatting options for jsonc-effect surgical edits. */
const JSONC_FORMAT: Partial<JsoncFormattingOptions> = { tabSize: 1, insertSpaces: false };

/** Available presets. */
type PresetType = "minimal" | "standard" | "silk";

/**
 * Check if a preset includes the ShellScripts handler.
 *
 * @param preset - The preset to check
 * @returns True if the preset includes ShellScripts (standard and silk)
 */
function presetIncludesShellScripts(preset: PresetType): boolean {
	return preset !== "minimal";
}

/**
 * Check if a preset includes markdown tooling.
 *
 * @param preset - The preset to check
 * @returns True if the preset includes Markdown (standard and silk)
 */
function presetIncludesMarkdown(preset: PresetType): boolean {
	return preset !== "minimal";
}

/**
 * Generate the lint-staged config file content.
 *
 * @param preset - The preset to use
 * @returns Config file content
 */
function generateConfigContent(preset: PresetType): string {
	return `/**
 * lint-staged configuration
 * Generated by savvy-lint init
 */
import { Preset } from "@savvy-web/lint-staged";

export default Preset.${preset}();
`;
}

/**
 * Write or update the markdownlint-cli2 config file.
 *
 * @param fs - FileSystem service
 * @param preset - The active preset
 * @param force - Whether to overwrite the entire file
 * @returns Effect that manages the markdownlint config
 */
function writeMarkdownlintConfig(fs: FileSystem.FileSystem, preset: PresetType, force: boolean) {
	return Effect.gen(function* () {
		const configExists = yield* fs.exists(MARKDOWNLINT_CONFIG_PATH);
		const fullTemplate = JSON.stringify(MARKDOWNLINT_TEMPLATE, null, "\t");

		if (!configExists) {
			// File missing → write full template
			yield* fs.makeDirectory("lib/configs", { recursive: true });
			yield* fs.writeFileString(MARKDOWNLINT_CONFIG_PATH, `${fullTemplate}\n`);
			yield* Effect.log(`${CHECK_MARK} Created ${MARKDOWNLINT_CONFIG_PATH}`);
			return;
		}

		if (preset !== "silk") {
			// Standard preset: don't manage existing files
			yield* Effect.log(`${CHECK_MARK} ${MARKDOWNLINT_CONFIG_PATH}: exists (not managed by ${preset} preset)`);
			return;
		}

		if (force) {
			// Force: overwrite entire file with fresh template
			yield* fs.writeFileString(MARKDOWNLINT_CONFIG_PATH, `${fullTemplate}\n`);
			yield* Effect.log(`${CHECK_MARK} Replaced ${MARKDOWNLINT_CONFIG_PATH} (--force)`);
			return;
		}

		// Silk preset, no force: surgical management of $schema + config
		const existingText = yield* fs.readFileString(MARKDOWNLINT_CONFIG_PATH);
		const existingParsed = (yield* parse(existingText)) as Record<string, unknown>;

		let updatedText = existingText;
		let schemaUpdated = false;

		// Always update $schema silently
		if (existingParsed.$schema !== MARKDOWNLINT_SCHEMA) {
			const edits = yield* modify(updatedText, ["$schema"], MARKDOWNLINT_SCHEMA, { formattingOptions: JSONC_FORMAT });
			updatedText = yield* applyEdits(updatedText, edits);
			schemaUpdated = true;
		}

		// Compare config with isDeepStrictEqual
		const existingConfig = existingParsed.config as Record<string, unknown> | undefined;
		const configMatches = existingConfig !== undefined && isDeepStrictEqual(existingConfig, MARKDOWNLINT_CONFIG);

		if (!configMatches) {
			yield* Effect.log(
				`${WARNING} ${MARKDOWNLINT_CONFIG_PATH}: config rules differ from template (use --force to overwrite)`,
			);
			// Still write schema update if it changed
			if (schemaUpdated) {
				yield* fs.writeFileString(MARKDOWNLINT_CONFIG_PATH, updatedText);
				yield* Effect.log(`${CHECK_MARK} Updated $schema in ${MARKDOWNLINT_CONFIG_PATH}`);
			}
			return;
		}

		if (schemaUpdated) {
			yield* fs.writeFileString(MARKDOWNLINT_CONFIG_PATH, updatedText);
			yield* Effect.log(`${CHECK_MARK} Updated $schema in ${MARKDOWNLINT_CONFIG_PATH}`);
		} else {
			yield* Effect.log(`${CHECK_MARK} ${MARKDOWNLINT_CONFIG_PATH}: up-to-date`);
		}
	});
}

/**
 * Find and sync biome config `$schema` URLs to match the peer dependency version.
 *
 * @returns Effect that syncs biome schemas and logs results
 */
function syncBiomeSchemas() {
	return Effect.gen(function* () {
		const version = process.env.__BIOME_PEER_VERSION__;
		if (!version) return;

		const syncer = yield* BiomeSchemaSync;
		const result = yield* syncer.sync(version);

		for (const configPath of result.current) {
			yield* Effect.log(`${CHECK_MARK} ${configPath}: biome $schema up-to-date`);
		}
		for (const configPath of result.updated) {
			yield* Effect.log(`${CHECK_MARK} Updated $schema in ${configPath}`);
		}
	});
}

const forceOption = Options.boolean("force").pipe(
	Options.withAlias("f"),
	Options.withDescription("Overwrite entire hook file (not just managed section)"),
	Options.withDefault(false),
);

const configOption = Options.text("config").pipe(
	Options.withAlias("c"),
	Options.withDescription("Relative path for the lint-staged config file (from repo root)"),
	Options.withDefault(DEFAULT_CONFIG_PATH),
);

const presetOption = Options.choice("preset", ["minimal", "standard", "silk"]).pipe(
	Options.withAlias("p"),
	Options.withDescription("Preset to use: minimal, standard, or silk"),
	Options.withDefault("silk" as const),
);

/**
 * Make a file executable.
 *
 * @param path - File path to make executable
 * @returns Effect that makes the file executable
 */
function makeExecutable(path: string) {
	return Effect.tryPromise(() => import("node:fs/promises").then((fs) => fs.chmod(path, EXECUTABLE_MODE)));
}

/**
 * Write a hook file with create/update/force logic.
 *
 * @param fs - FileSystem service
 * @param section - ManagedSection service
 * @param hookPath - Path to the hook file
 * @param block - The section block to sync
 * @param comment - Header comment for new hook files
 * @param force - Whether to overwrite the entire file
 * @returns Effect that writes the hook
 */
function writeHook(
	fs: FileSystem.FileSystem,
	section: ManagedSection["Type"],
	hookPath: string,
	block: SectionBlock,
	comment: string,
	force: boolean,
) {
	return Effect.gen(function* () {
		const hookExists = yield* fs.exists(hookPath);
		const header = `#!/usr/bin/env sh\n# ${comment}\n# Custom hooks can go above or below the managed section\n`;

		if (!hookExists || force) {
			if (!hookExists) {
				yield* fs.makeDirectory(".husky", { recursive: true });
			}
			yield* fs.writeFileString(hookPath, header);
		}

		const result = yield* section.sync(hookPath, block);
		yield* makeExecutable(hookPath);

		if (!hookExists) {
			yield* Effect.log(`${CHECK_MARK} Created ${hookPath}`);
		} else if (force) {
			yield* Effect.log(`${CHECK_MARK} Replaced ${hookPath} (--force)`);
		} else {
			yield* SyncResult.$match(result, {
				Created: () => Effect.log(`${CHECK_MARK} Added managed section to ${hookPath}`),
				Updated: () => Effect.log(`${CHECK_MARK} Updated managed section in ${hookPath}`),
				Unchanged: () => Effect.log(`${CHECK_MARK} ${hookPath}: up-to-date`),
			});
		}
	});
}

/**
 * Init command implementation.
 *
 * @remarks
 * Creates the necessary configuration files for lint-staged:
 * - `.husky/pre-commit` hook with managed section
 * - `.husky/post-checkout` and `.husky/post-merge` hooks (when preset includes ShellScripts)
 * - `.markdownlint-cli2.jsonc` config (when preset includes Markdown)
 * - lint-staged config at the specified path
 *
 * The managed section feature allows users to add custom hooks above/below
 * the savvy-lint section without them being overwritten on updates.
 */
export const initCommand = Command.make(
	"init",
	{ force: forceOption, config: configOption, preset: presetOption },
	({ force, config, preset }) =>
		Effect.gen(function* () {
			const fs = yield* FileSystem.FileSystem;
			const section = yield* ManagedSection;

			if (config.startsWith("/")) {
				yield* Effect.fail(new Error("Config path must be relative to repository root, not absolute"));
			}

			yield* Effect.log("Initializing lint-staged configuration...\n");

			// Write pre-commit hook (always)
			yield* writeHook(
				fs,
				section,
				HUSKY_HOOK_PATH,
				preCommitBlock(config),
				"Pre-commit hook with savvy-lint managed section",
				force,
			);

			// Write post-checkout and post-merge hooks (when preset includes ShellScripts)
			if (presetIncludesShellScripts(preset)) {
				const shellBlock = shellScriptsBlock();

				yield* writeHook(
					fs,
					section,
					POST_CHECKOUT_HOOK_PATH,
					shellBlock,
					"Post-checkout hook with savvy-lint managed section",
					force,
				);

				yield* writeHook(
					fs,
					section,
					POST_MERGE_HOOK_PATH,
					shellBlock,
					"Post-merge hook with savvy-lint managed section",
					force,
				);
			}

			// Write markdownlint config (when preset includes Markdown)
			if (presetIncludesMarkdown(preset)) {
				yield* writeMarkdownlintConfig(fs, preset, force);
			}

			// Sync biome $schema URLs
			yield* syncBiomeSchemas().pipe(
				Effect.catchTag("BiomeSyncError", (e) => Effect.log(`${WARNING} Could not sync biome $schema: ${e.message}`)),
			);

			// Handle config file
			const configExists = yield* fs.exists(config);

			if (configExists && !force) {
				yield* Effect.log(`${WARNING} ${config} already exists (use --force to overwrite)`);
			} else {
				const configDir = dirname(config);
				if (configDir && configDir !== ".") {
					yield* fs.makeDirectory(configDir, { recursive: true });
				}
				yield* fs.writeFileString(config, generateConfigContent(preset));
				yield* Effect.log(`${CHECK_MARK} Created ${config} (preset: ${preset})`);
			}

			yield* Effect.log("\nDone! Lint-staged is ready to use.");
		}),
).pipe(Command.withDescription("Initialize lint-staged configuration and husky hooks"));
